import './globals.css'
import PageLayout from '@/components/pageLayout'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PageLayout>
          {children} {/* This will pass children to PageLayout */}
        </PageLayout>
      </body>
    </html>
  )
}
